# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOOy4i0ySYdBfsnQ8HeDNM6bFPUNuPeU

#MOVIE RATING PREDICTION WITH PYTHON
"""

import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('IMDb Movies India.csv',encoding="latin1")

data.head(10)

data.tail(10)

data.shape

print("Number of rows-",data.shape[0])
print("Number of coloumns-",data.shape[1])

print(data.info())

print("Any missing value??",data.isnull().values.any())

data.isnull().sum()

sns.heatmap(data.isnull())

per_missing = data.isnull().sum()*100/len(data)
print(per_missing)

data.dropna(axis=0)

dup_data=data.duplicated().any()
print("Can any duplicate values be found in the dataset??",dup_data)

data=data.drop_duplicates()
print(data)

data.describe(include='all')

data.columns

sns.barplot (x='Actor 1',y='Rating',data=data)
plt.title("Actor and Rating")
plt.show()

data.groupby('Year')['Rating'].mean()

data.groupby('Director')['Rating'].mean()

top10_len=data.nlargest(10,'Rating')[['Name','Rating']]\
.set_index('Name')

top10_len

sns.barplot(x='Rating',y=top10_len.index,data=top10_len)
plt.title("Top 10 Movies with high rating")
plt.show

data.columns

data['Year'].value_counts()

sns.countplot(x='Year',data=data)
plt.title("Number of Movies per Year")
plt.show()

data.columns

top10_len=data.nlargest(10,'Rating')[['Name','Rating','Director']]\
.set_index('Name')

top10_len

data.columns

data.groupby('Year')['Rating'].mean()

def rating(rating):
  if rating>=7.0:
    return "Excellent"
  elif rating>=6.0:
    return "Good"
  else:
    return "Average"

data['rating_cat']=data['Rating'].apply(rating)
data.head(10)

data.columns

data['Genre'].dtype

data['Genre'].str.contains('Action')

data.columns

data['Genre']