# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8jrIu07VwpHIG_x3IdIPUEqslX7y17H

SALES PREDICTION USING PYTHON
"""

# Analysing the data
import pandas as pd
data = pd.read_csv('advertising.csv')

data.head()

data.info()

data.isnull().sum()

data['Radio'].mean()

data['TV'].mean()

data['Sales'].mean()

data.describe()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,6))
sns.displot(data['TV'])
plt.show()

plt.figure(figsize=(6,6))
sns.displot(data['Radio'])
plt.show()

plt.figure(figsize=(6,6))
sns.displot(data['Sales'])
plt.show()

plt.figure(figsize=(6,6))
sns.displot(data['Newspaper'])
plt.show()

sns.pairplot(data, x_vars=['TV','Radio','Newspaper'], y_vars='Sales',kind='scatter')
plt.show()

sns.heatmap(data.corr(),annot= True)
plt.show()